conv1 = ["Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome.",
    "What Day is Today?",
    '{}/{}/{} - {}:{}'.format(now.day,now.month,now.year,now.hour,now.minute),
    'What is your name?',
    'Thor',
    'Nice To meet you Thor',
    'Nice to meet you too User',
    'Can you help me?',
    'Of course, How can I help?']